name: vyper-builds

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    # every 3 hours on the 19th minute
    - cron: "19 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Configure git
        run: |
          git config --global user.name "vyper commit bot"
          git config --global user.email "vyper-bot@users.noreply.github.com"

      - name: Checkout the 'builds' branch
        run: |
          git checkout builds
          git merge main

      - name: Fetch
        run: python fetch.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Commit and push
        run: |
          git add all-commits/ releases/
          # swallow git "nothing added to commit" error; we might have
          # a merge commit which we want to push.
          git commit -m "add binaries" || echo "no new binaries" 1>&2
          git push
