name: vyper-builds

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    # every 3 hours on the 19th minute
    - cron: "19 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Install dependencies via apt-get
        run: |
          sudo apt-get update -q
          sudo apt-get install -y -q git

      - name: Checkout the 'builds' branch
        run: |
          git checkout builds
          git merge main

      - name: Fetch
        run: python fetch.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Clean symlinks
        # clean bad symlinks that were created in the previous step
        # https://unix.stackexchange.com/a/314975
        run: find . -xtype l -delete releases/


      - name: Commit and push
        run: |
          git config --global user.name "vyper commit bot"
          git config --global user.email "vyper-bot@users.noreply.github.com"
          git add builds/ releases/
          git commit -m "add binaries"
          git push
        continue-on-error: true
